prog ::= prog classDecl classDeclList
;

// add inheritance

classDecl ::= CLASS ID LCURLY methodDeclList RCURLY
classDeclList ::= classDecl
                    | classDecl COMMA classDeclList
                    |

expr ::= expr PLUS term
         | expr MINUS term
         | term
;

term ::= term MULT factor
         | factor
;

factor ::= MINUS operand
		 | operand
;

operand ::= LPAREN expr RPAREN
         | NUMBER
//          | MAX LPAREN expr:e commaexprlist:el RPAREN {: el.addFirst(e); RESULT = new MaxExpr(el); :}

;


commaexprlist ::= COMMA expr commaexprlist
		 | /* empty */

;
